version: "3"

services:
  db:
    image: postgres:11
    hostname: ec2-174-129-43-40.compute-1.amazonaws.com
    environment:
      - POSTGRES_USER=argoqhirukoixl
      - POSTGRES_PASSWORD=83405daca6457af89707205fbfaf947962f5d5ace638c0a32c75eae6aa247ea8
      - POSTGRES_DB=d203letc58un47
    ports:
      - "5432:5432"
  backend:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
