# Generated by Django 2.2.7 on 2019-11-30 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('choices', '0004_delete_answerusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0006_auto_20191126_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedQuesttionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_answer', to='answers.Answer')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='choices.Choice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
